repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0  # Use the latest stable version
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use latest
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
