apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener-helm.fullname" . }}
  labels:
    {{- include "url-shortener-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "url-shortener-helm.selectorLabels" . | nindent 4 }}
